# 1.1 - Numpy  (Numerical Python)

**[Documentación](https://numpy.org/doc/stable/)**

**[Código fuente](https://github.com/numpy/numpy)**


![numpy](images/numpy.png)

NumPy es el paquete fundamental para computación cientifíca en python. Es una librería de python nos permite manejar vectores, matrices, [tensores](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) (arrays multidimensionales) y además realizar todas las operaciones matemáticas y lógicas de los mismos, como la manipulación de la dimensión, ordenado, selección, I/O, operaciones estadísticas, transformadas de Fourier, simulación aleatoria y un largo etcétera. Constituye la herramienta de álgebra lineal.

## Recordatorio de álgebra

+ Contenidos:

    + Concepto de tensor
    + Operaciones con vectores
        + Concepto de espacio vectorial y base
        + Suma de vectores
        + Producto escalar
        + Producto vectorial
    + Operaciones con matrices
        + Suma de matrices
        + Producto matricial
        + Matriz Identidad
        + Matriz Traspuesta (Hermítica)
        + Matriz Inversa 
        + Determinate

### Tensor

La palabra ['tensor'](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) se utiliza a menudo como abreviatura de campo tensorial, que es un valor tensorial definido en cada punto en una variedad. El primero en utilizar esta palabra fue William Rowan Hamilton en 1846, empleándola para lo que actualmente se conoce como módulo y fue Woldemar Voigt en 1899 quien la empleó en su acepción actual. La palabra tensor proviene del latín tensus, participio pasado de tendere 'estirar, extender'. El nombre se extendió porque la teoría de la elasticidad fue una de las primeras aplicaciones físicas donde se usaron tensores. Gregorio Ricci-Curbastro en 1890 desarrolló la notación actual con el nombre de geometría diferencial absoluta, y se popularizó con la publicación de Cálculo Diferencial Absoluto de Tullio Levi-Civita en 1900. Con la introducción de la teoría de la relatividad general por parte de Albert Einstein alrededor de 1915 se encontró su aplicación más pragmática. La Relatividad General es netamente tensorial. Einstein había aprendido del mismo Levi-Civita el uso de tensores con gran dificultad.

Podemos pensar en un tensor como la generalización del ente algebraico. Con un ejemplo se verá más claro.

Un **número**, cualquier número, $2$, $3.6$, $\pi$, $\phi$, $\sqrt{2}$, es un **tensor de rango $0$**.

Un **vector**, cualquier vector, sea como sea su longitud, $(1, 2, 3)$, $(0, 5, 2, 1, 5)$, $(9,2)$, es un **tensor de rango $1$**.

Una **matriz**, cualquier matriz, sean cuales sean sus dimensiones, es un **tensor de rango $2$**.

Un **cubo de Rubik** por ejemplo es un **tensor de rango $3$**.

Pensar en dimensiones superiores es complicado por no decir imposible, pero se pueden interpretar a través del contenido. Una **bolsa llena de cubos de Rubik** es un **tensor de rango $4$**.

Una **caja llena de bolsas que están llenas de cubos de Rubik es un tensor de rango $5$**.

Y así sucesivamente.

### Operaciones con vectores

**Espacio vectorial**

La definición matemática de [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) implica los conceptos de conjunto, ley de composición(operación) interna y ley de composición externa, definida sobre un segundo conjunto. Resumiendo, un espacio vectorial es una estructura creada sobre un conjunto no vacío con ambas leyes de composición. A los elementos de un espacio vectorial se les llama vectores.

Veamos un ejemplo:

Un espacio vectorial es el espacio tridimensional ${\Bbb R}^{3}$. Los elementos de ${\Bbb R}^{3}$ son vectores, por lo que la ley de composición interna es la suma de vectores. Para la ley de composición externa se necesita otro conjunto, que en esta caso son los números reales ${\Bbb R}$, y queda definida como el producto por escalares, multiplicar un vector por un número.



**Base vectorial**

Una [base](https://es.wikipedia.org/wiki/Base_(%C3%A1lgebra)) es un conjunto de vectores {$v_{1}, v_{2}, v_{3}, ... ,v_{n}$} que cumplen las siguientes propiedades:

+ Todos los elementos de la base pertenecen al mismo espacio vectorial.
+ Los elementos de la base forman un sistema linealmente independiente (ninguno es combinación lineal de los demás).
+ Cualquier elemento del espacio vectorial se puede escribir como combinación lineal de los elementos de la base (es lo que se llama sistema generador del espacio vectorial).

Ejemplo:

En ${\Bbb R}^{3}$, la base principal (llamada canónica) es {$(1,0,0), (0,1,0), (0,0,1)$}. Todos esos vectores pertenecen a ${\Bbb R}^{3}$, son linealmente independientes(ninguno puede ser una suma de los otros) y cualquier otro vector en ${\Bbb R}^{3}$ se puede representar como una suma de esos tres, una combinación lineal. No es única, otra base de ${\Bbb R}^{3}$ podría ser {$(1,1,1), (1,1,0), (1,0,0)$}



**Suma de vectores**

Los vectores se suman por componentes, lo que implica que ambos tienen la misma longitud. Por ejemplo en ${\Bbb R}^{3}$:

$$\vec{A}=A_{x}\vec{i}+A_{y}\vec{j}+A_{z}\vec{k}$$

$$\vec{B}=B_{x}\vec{i}+B_{y}\vec{j}+B_{z}\vec{k}$$

$$\vec{A}+\vec{B}=(B_{x}+A_{x})\vec{i}+(B_{y}+A_{y})\vec{j}+(B_{z}+A_{z})\vec{k}$$

$$$$

$$\vec{A}=(1,8,9)$$

$$\vec{B}=(4,3,0)$$

$$\vec{A}+\vec{B}=(5,11,9)$$



**Producto escalar**

Hay que diferenciar entre producto por escalares, un número por un vector resultando un vector, y el productor escalar donde se multiplican dos vectores resultando un número, un escalar.

+ Producto por escalares:

Se realiza elemento a elemento la multiplicación por el número:

$$\vec{A}=(1,8,9)$$

$$2*\vec{A}=(2,16,18)$$

+ Productos escalar:

Se realiza multiplicando elemento un vector fila por un vector columna y sumando los resultados. Hay que tener en cuenta, igual que en la suma, que ambos vectores tienen el mismo número de elementos. También se le llama producto punto (dot product) o producto interno (inner product).

$$\vec{A}\cdot\vec{B}=(1, 8, 9)\cdot\begin{pmatrix}4\\3\\0\end{pmatrix} = 1·4+8·3+9·0 = 4+24+0 = 28$$



**Producto vectorial**

En este caso, se multiplican dos vectores resultando otro vector. La manera más fácil de hacerlo es a través de un determinante:


$$\vec{A}\times \vec{B} = \begin{vmatrix}
\hat{\imath}&\hat{\jmath}&\hat{k}\\
1 & 8 & 9 \\
4 & 3 & 0
\end{vmatrix} = \begin{vmatrix}
8 & 9 \\
3 & 0
\end{vmatrix}·\hat{\imath} - 
\begin{vmatrix}
1 & 9 \\
4 & 0
\end{vmatrix}·\hat{\jmath} +
\begin{vmatrix}
1 & 8 \\
4 & 3
\end{vmatrix}·\hat{k} = (8·0-9·3)·\hat{\imath}-(1·0-9·4)·\hat{\jmath}+(1·3-8·4)·\hat{k}$$

$$\vec{A}\times \vec{B} = (-27, 36, -29)$$

### Operaciones con matrices


**Suma de matrices**

Las matrices tienen definidas sus dimensiones sugún el número de filas($m$) y de columnas($n$), y se representan como $A_{mxn}$. Para sumar matrices las dimensiones tienen que ser las mismas, igual que ocurría con los vectores, y se realiza elemento a elemento (element wise):


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}+\begin{pmatrix}
0 & 0 & 3 \\
2 & 2 & 7 
\end{pmatrix}=\begin{pmatrix}
5 & 7 & 4 \\
6 & 2 & 9 
\end{pmatrix}$$



**Producto matricial**

Para multiplicar matrices tenemos que tener en cuenta las dimensiones, porque el producto matricial no es conmutativo e incluso a veces no se puede realizar. El número de columnas de la primera matriz tiene que ser igual que el número de filas de la segunda y el resultado tendrá el número de filas de la primera y el número de columnas de la segunda. Es decir:

$$A_{rxn}\cdot B_{nxq} = C_{rxq}$$


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}\cdot\begin{pmatrix}
0 & 0 \\
2 & 3 \\
2 & 7 
\end{pmatrix}=\begin{pmatrix}
5·0+7·2+1·2 & 5·0+7·3+1·7 \\
4·0+0·2+2·2 & 4·0+0·3+2·7
\end{pmatrix}=\begin{pmatrix}
18 & 28 \\
4 & 14
\end{pmatrix}$$



**Matriz Identidad**

Elemento neutro de la multiplicación, solo $1_s$ en la diagonal:

$$I = \begin{pmatrix}
1&0&\cdots&0&0\\
0&1&\cdots&0&0\\
\vdots&\vdots&\ddots&\vdots&\vdots\\
0&\cdots&\cdots&\cdots&0\\
0&0&\cdots&1&0\\
0&0&\cdots&0&1\\
\end{pmatrix}$$



**Matriz traspuesta  (hermítica)**

La traspuesta $A^{T}$ de una matriz $A$ puede ser obtenida reflejando los elementos a lo largo de su diagonal.

$$A=\begin{pmatrix}
5 & 7 & 9 \\
4 & 0 & 7 \\
1 & 2 & 2
\end{pmatrix}$$

$$A^{T}=\begin{pmatrix}
5 & 4 & 1 \\
7 & 0 & 2 \\
9 & 7 & 2
\end{pmatrix}$$


Se le dice hermítica si los elementos son números complejos, es la traspuesta conjugada (el conjugado de $x+iy$ es $x-iy$).


**Matriz Inversa**

¿Como se dividen las matrices? Se multiplica por la inversa. El cálculo de la matriz inversa es:

$$A= \begin{pmatrix}
       a_{11} & a_{12} \\ 
       a_{21} & a_{22}
    \end{pmatrix}$$
    
    
$$A^{-1}=\begin{pmatrix}
a_{11} & a_{12} \\ 
a_{21} & a_{22}
\end{pmatrix}^{-1}
=\frac{1}{\lvert A\rvert}
\begin{pmatrix}
a_{22} & -a_{12} \\ 
-a_{21} &  a_{11}
\end{pmatrix}$$


**Determinante**

$$A=\begin{pmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{pmatrix}$$
  

$$$$


$$det(A)=\begin{vmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 0 & 0 \\ 
    -2 & 1 & 0 \\ 
    -2 & 0 & 1
  \end{vmatrix}\cdot
  \begin{vmatrix}
    1 & 4 & 1 \\ 
    2 & 6 & 3 \\ 
    2 & 10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 4 & 1 \\ 
    0 & -2 & 1 \\ 
    0 & 2 & 1
  \end{vmatrix}
  =
  \begin{vmatrix}
    -2 & 1 \\ 
    2 & 1
  \end{vmatrix}
  =-4$$
  
  

El principal uso del determinante es para realizar el cáculo de la matriz inversa, ya que si el determinante de una matriz es 0 es matriz no tiene matriz inversa

**Veamos algo de todo esto en python:**


**Arrays**

In [1]:
%pip install numpy

In [2]:
import numpy as np

In [3]:
# numero, o tensor de rango 0
type(np.random.random(1))

numpy.ndarray

In [5]:
np.random.random(1)

array([0.69408748])

In [9]:
# vector, tensor de rango 1
vector = np.random.random(5)

vector

array([0.12853713, 0.62661716, 0.50102846, 0.4953363 , 0.35817228])

In [10]:
type(vector)

numpy.ndarray

In [11]:
# producto escalar
vector_2 = np.random.random(5)

In [15]:
vector_2

array([0.65029382, 0.54177741, 0.38661326, 0.65593446, 0.95703113])

In [12]:
p_escalar = np.dot(vector, vector_2)

In [13]:
p_escalar

1.2844683393936165

In [14]:
2 * vector_2

array([1.30058764, 1.08355482, 0.77322652, 1.31186892, 1.91406225])

In [16]:
# matriz, tensor de rango 2

matriz = np.random.random((10,5))

matriz


array([[0.90486208, 0.87713097, 0.87576206, 0.45924109, 0.57861838],
       [0.35176071, 0.8288533 , 0.44128122, 0.79732528, 0.34296071],
       [0.31051913, 0.44899256, 0.91587882, 0.20653487, 0.06429239],
       [0.92712852, 0.73555388, 0.84575237, 0.07835244, 0.22481925],
       [0.86823526, 0.48125145, 0.42416677, 0.70081709, 0.38932363],
       [0.72356205, 0.95216341, 0.39680908, 0.87109203, 0.7769021 ],
       [0.36501708, 0.20384152, 0.4531161 , 0.38071829, 0.18384882],
       [0.60585984, 0.12877656, 0.93462732, 0.44645968, 0.761247  ],
       [0.03046927, 0.23549773, 0.95594511, 0.33063498, 0.87160176],
       [0.39073941, 0.78146196, 0.46042978, 0.1701343 , 0.24417127]])

In [17]:
type(matriz)

numpy.ndarray

In [18]:
matriz_ones = np.ones((10,5))

matriz_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
matriz_a_manita = [[1, 34, 54],
                  [2, 3, 5],
                  [3, 56, 98]]

In [20]:
type(matriz_a_manita)

list

In [22]:
np.array(matriz_a_manita).tolist()

[[1, 34, 54], [2, 3, 5], [3, 56, 98]]

In [28]:
# dimension

matriz.shape

(10, 5)

In [30]:
# nº de elementos

matriz.size

50

In [31]:
# primera fila de la matriz

matriz[0]

array([0.90486208, 0.87713097, 0.87576206, 0.45924109, 0.57861838])

In [40]:
matriz[0, :3]

array([0.90486208, 0.87713097, 0.87576206])

In [32]:
matriz[3][2]

0.8457523700584322

In [39]:
# primera columna

matriz[:, 0]

array([0.90486208, 0.35176071, 0.31051913, 0.92712852, 0.86823526,
       0.72356205, 0.36501708, 0.60585984, 0.03046927, 0.39073941])

In [34]:
matriz

array([[0.90486208, 0.87713097, 0.87576206, 0.45924109, 0.57861838],
       [0.35176071, 0.8288533 , 0.44128122, 0.79732528, 0.34296071],
       [0.31051913, 0.44899256, 0.91587882, 0.20653487, 0.06429239],
       [0.92712852, 0.73555388, 0.84575237, 0.07835244, 0.22481925],
       [0.86823526, 0.48125145, 0.42416677, 0.70081709, 0.38932363],
       [0.72356205, 0.95216341, 0.39680908, 0.87109203, 0.7769021 ],
       [0.36501708, 0.20384152, 0.4531161 , 0.38071829, 0.18384882],
       [0.60585984, 0.12877656, 0.93462732, 0.44645968, 0.761247  ],
       [0.03046927, 0.23549773, 0.95594511, 0.33063498, 0.87160176],
       [0.39073941, 0.78146196, 0.46042978, 0.1701343 , 0.24417127]])

In [41]:
# cubo, tensor de rango 3

cubo = np.random.random((3,3,2))

cubo

array([[[0.17955228, 0.88438704],
        [0.34779724, 0.05975896],
        [0.76177256, 0.54262149]],

       [[0.78619752, 0.50757626],
        [0.09685475, 0.94609689],
        [0.24117818, 0.12269995]],

       [[0.73674726, 0.88143013],
        [0.92114852, 0.98024823],
        [0.49510534, 0.49983011]]])

In [43]:
#help(cubo)

In [46]:
cubo[0][2][1]

0.5426214889699418

In [48]:
# tensor de rango 4

tensor = np.random.random((5,3,3,2))

tensor[0]

array([[[0.2916434 , 0.77971117],
        [0.23588552, 0.71029288],
        [0.61202536, 0.21168583]],

       [[0.37756141, 0.72722167],
        [0.48706535, 0.03094226],
        [0.50543632, 0.63045527]],

       [[0.50587556, 0.06833017],
        [0.26246406, 0.58009945],
        [0.4152612 , 0.2461388 ]]])

In [49]:
type(tensor)

numpy.ndarray

In [55]:
# de listas a arrays

lst = [1,2,3,4]

array = np.array(lst)

type(array)

numpy.ndarray

In [56]:
array.shape

(4,)

In [52]:
lst_lts = [[1,2,3],
          [4,5,6],
          [7,8,9]]

array_2 = np.array(lst_lts)

array_2.shape

(3, 3)

**Operaciones matemáticas**

In [57]:
matriz

array([[0.90486208, 0.87713097, 0.87576206, 0.45924109, 0.57861838],
       [0.35176071, 0.8288533 , 0.44128122, 0.79732528, 0.34296071],
       [0.31051913, 0.44899256, 0.91587882, 0.20653487, 0.06429239],
       [0.92712852, 0.73555388, 0.84575237, 0.07835244, 0.22481925],
       [0.86823526, 0.48125145, 0.42416677, 0.70081709, 0.38932363],
       [0.72356205, 0.95216341, 0.39680908, 0.87109203, 0.7769021 ],
       [0.36501708, 0.20384152, 0.4531161 , 0.38071829, 0.18384882],
       [0.60585984, 0.12877656, 0.93462732, 0.44645968, 0.761247  ],
       [0.03046927, 0.23549773, 0.95594511, 0.33063498, 0.87160176],
       [0.39073941, 0.78146196, 0.46042978, 0.1701343 , 0.24417127]])

In [1]:
# sumar todo

In [58]:
matriz.sum()

26.734540663818123

In [59]:
# suma por columnas 

matriz.sum(axis=0)

array([5.47815333, 5.67352335, 6.70376862, 4.44131006, 4.4377853 ])

In [60]:
# suma por filas 

matriz.sum(axis=1)

array([3.69561457, 2.76218121, 1.94621778, 2.81160647, 2.8637942 ,
       3.72052866, 1.5865418 , 2.87697039, 2.42414885, 2.04693672])

In [61]:
matriz.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [62]:
cubo.sum(axis=2)

array([[1.06393931, 0.40755619, 1.30439405],
       [1.29377377, 1.04295163, 0.36387813],
       [1.6181774 , 1.90139675, 0.99493545]])

In [64]:
# suma por cubos

tensor.sum(axis=0)

array([[[2.21824765, 3.75359991],
        [1.95364795, 2.14532912],
        [2.36696221, 1.74388543]],

       [[3.52363737, 1.77669281],
        [1.65588567, 2.57530896],
        [1.8744709 , 3.20018281]],

       [[3.47385102, 2.21618842],
        [1.97339689, 1.95475264],
        [1.86434477, 2.50803925]]])

In [66]:
# suma por capas del cubo
tensor.sum(axis=1)

array([[[1.17508037, 1.575263  ],
        [0.98541492, 1.32133459],
        [1.53272288, 1.08827991]],

       [[1.89707006, 0.87828876],
        [1.3912274 , 1.00334942],
        [1.51567539, 1.32976821]],

       [[1.90062971, 2.17217046],
        [1.34453905, 1.79435697],
        [0.62807485, 2.21859289]],

       [[2.17303548, 1.38165453],
        [1.31890872, 1.04236539],
        [1.9015247 , 1.3972473 ]],

       [[2.06992042, 1.73910438],
        [0.54284042, 1.51398435],
        [0.52778005, 1.41821917]]])

In [67]:
# suma por filas
tensor.sum(axis=2)

array([[[1.13955428, 1.70168989],
        [1.37006307, 1.3886192 ],
        [1.18360082, 0.89456842]],

       [[1.95345698, 0.62590487],
        [1.91786622, 1.66851439],
        [0.93264966, 0.91698714]],

       [[1.32868071, 1.9518407 ],
        [0.98356754, 2.45026465],
        [1.56099536, 1.78301497]],

       [[1.52759066, 1.7119342 ],
        [1.70482091, 0.65447428],
        [2.16105733, 1.45485873]],

       [[0.58957518, 1.6514448 ],
        [1.0776762 , 1.39031206],
        [1.47328951, 1.62955104]]])

In [69]:
tensor

array([[[[0.2916434 , 0.77971117],
         [0.23588552, 0.71029288],
         [0.61202536, 0.21168583]],

        [[0.37756141, 0.72722167],
         [0.48706535, 0.03094226],
         [0.50543632, 0.63045527]],

        [[0.50587556, 0.06833017],
         [0.26246406, 0.58009945],
         [0.4152612 , 0.2461388 ]]],


       [[[0.44685798, 0.5388611 ],
         [0.60186956, 0.06790273],
         [0.90472944, 0.01914103]],

        [[0.916659  , 0.05589437],
         [0.46820521, 0.67390604],
         [0.533002  , 0.93871398]],

        [[0.53355308, 0.28353329],
         [0.32115263, 0.26154064],
         [0.07794395, 0.3719132 ]]],


       [[[0.28864127, 0.64463891],
         [0.65843392, 0.56920655],
         [0.38160552, 0.73799523]],

        [[0.77061061, 0.55999228],
         [0.03231817, 0.95906885],
         [0.18063877, 0.93120352]],

        [[0.84137783, 0.96753928],
         [0.65378696, 0.26608156],
         [0.06583057, 0.54939413]]],


       [[[0.64544676, 0.8875689

In [68]:
# suma por columnas
tensor.sum(axis=3)

array([[[1.07135457, 0.9461784 , 0.8237112 ],
        [1.10478308, 0.51800761, 1.13589159],
        [0.57420572, 0.84256351, 0.66140001]],

       [[0.98571908, 0.66977229, 0.92387047],
        [0.97255337, 1.14211125, 1.47171598],
        [0.81708637, 0.58269328, 0.44985715]],

       [[0.93328018, 1.22764047, 1.11960076],
        [1.33060289, 0.99138702, 1.11184229],
        [1.80891711, 0.91986853, 0.6152247 ]],

       [[1.53301573, 0.85310412, 0.85340501],
        [0.99858419, 0.49144732, 0.86926368],
        [1.02309009, 1.01672267, 1.57610331]],

       [[1.44847799, 0.40228178, 0.3902602 ],
        [0.89380665, 1.08824144, 0.48594018],
        [1.46674015, 0.56630155, 1.06979885]]])

In [71]:
matriz

array([[0.90486208, 0.87713097, 0.87576206, 0.45924109, 0.57861838],
       [0.35176071, 0.8288533 , 0.44128122, 0.79732528, 0.34296071],
       [0.31051913, 0.44899256, 0.91587882, 0.20653487, 0.06429239],
       [0.92712852, 0.73555388, 0.84575237, 0.07835244, 0.22481925],
       [0.86823526, 0.48125145, 0.42416677, 0.70081709, 0.38932363],
       [0.72356205, 0.95216341, 0.39680908, 0.87109203, 0.7769021 ],
       [0.36501708, 0.20384152, 0.4531161 , 0.38071829, 0.18384882],
       [0.60585984, 0.12877656, 0.93462732, 0.44645968, 0.761247  ],
       [0.03046927, 0.23549773, 0.95594511, 0.33063498, 0.87160176],
       [0.39073941, 0.78146196, 0.46042978, 0.1701343 , 0.24417127]])

In [70]:
# minimo de una matriz
matriz.min()

0.030469266351234037

In [72]:
# máximo de una matriz
matriz.max()

0.955945105537743

In [73]:
# media de todo

matriz.mean()

0.5346908132763625

In [75]:
matriz.mean(axis=1)

array([0.73912291, 0.55243624, 0.38924356, 0.56232129, 0.57275884,
       0.74410573, 0.31730836, 0.57539408, 0.48482977, 0.40938734])

In [76]:
# desviacion standard

matriz.std()

0.28203488407030725

In [77]:
# varianza
matriz.var()

0.07954367583255163

In [79]:
# desviación standard a partir de la varianza
matriz.var() ** 0.5

0.28203488407030725

In [80]:
# suma de vectores

np.add(matriz[0], matriz[1])

array([1.25662279, 1.70598427, 1.31704328, 1.25656637, 0.92157908])

In [84]:
matriz_p = [[2,3],
            [3,2]]
array_p = np.array(matriz_p)

print('Suma vectorial', np.add(array_p[0], array_p[1]))

print('Suma ', sum(array_p[0], array_p[1]))

Suma vectorial [5 5]
Suma  [8 7]


In [81]:
sum(matriz[0], matriz[1])

array([4.04737528, 4.52446787, 4.13689579, 4.49293985, 4.03857528])

In [ ]:
# resta

In [ ]:
np.subtract(matriz[0], matriz[1])

In [85]:
# numeración científica
1e3

1000.0

In [86]:
1e-3

0.001

In [88]:
# elemento a elemento

np.multiply(matriz_p[0], matriz_p[1])

array([6, 6])

In [89]:
# producto escalar

np.dot(matriz_p[0], matriz_p[1])

12

In [91]:
# matriz transpuesta
matriz.T


array([[0.90486208, 0.35176071, 0.31051913, 0.92712852, 0.86823526,
        0.72356205, 0.36501708, 0.60585984, 0.03046927, 0.39073941],
       [0.87713097, 0.8288533 , 0.44899256, 0.73555388, 0.48125145,
        0.95216341, 0.20384152, 0.12877656, 0.23549773, 0.78146196],
       [0.87576206, 0.44128122, 0.91587882, 0.84575237, 0.42416677,
        0.39680908, 0.4531161 , 0.93462732, 0.95594511, 0.46042978],
       [0.45924109, 0.79732528, 0.20653487, 0.07835244, 0.70081709,
        0.87109203, 0.38071829, 0.44645968, 0.33063498, 0.1701343 ],
       [0.57861838, 0.34296071, 0.06429239, 0.22481925, 0.38932363,
        0.7769021 , 0.18384882, 0.761247  , 0.87160176, 0.24417127]])

In [92]:
matriz_3 = np.random.random((3,2))

matriz_3

array([[0.15070878, 0.56689701],
       [0.97320995, 0.13927288],
       [0.1439224 , 0.35631316]])

In [93]:
matriz_3.T

array([[0.15070878, 0.97320995, 0.1439224 ],
       [0.56689701, 0.13927288, 0.35631316]])

In [94]:
# suma acumulada
np.cumsum(matriz_3)

array([0.15070878, 0.71760579, 1.69081573, 1.83008862, 1.97401101,
       2.33032418])

In [95]:
# producto acumulado
np.cumprod(matriz_3)

array([0.15070878, 0.08543636, 0.08314751, 0.01158019, 0.00166665,
       0.00059385])

In [97]:
# infinito
type(np.inf)

float

In [99]:
# nan
type(np.nan)

float

In [101]:
type(matriz.tolist())

list

In [108]:
# determinante

np.linalg.det(matriz_3[:2, :])

-0.5307201575862195

**Dimensiones**

In [109]:
matriz.shape

(10, 5)

In [112]:
matriz.reshape(5,5,2)

array([[[0.90486208, 0.87713097],
        [0.87576206, 0.45924109],
        [0.57861838, 0.35176071],
        [0.8288533 , 0.44128122],
        [0.79732528, 0.34296071]],

       [[0.31051913, 0.44899256],
        [0.91587882, 0.20653487],
        [0.06429239, 0.92712852],
        [0.73555388, 0.84575237],
        [0.07835244, 0.22481925]],

       [[0.86823526, 0.48125145],
        [0.42416677, 0.70081709],
        [0.38932363, 0.72356205],
        [0.95216341, 0.39680908],
        [0.87109203, 0.7769021 ]],

       [[0.36501708, 0.20384152],
        [0.4531161 , 0.38071829],
        [0.18384882, 0.60585984],
        [0.12877656, 0.93462732],
        [0.44645968, 0.761247  ]],

       [[0.03046927, 0.23549773],
        [0.95594511, 0.33063498],
        [0.87160176, 0.39073941],
        [0.78146196, 0.46042978],
        [0.1701343 , 0.24417127]]])

In [114]:
matriz.flatten().shape

(50,)

In [115]:
matriz

array([[0.90486208, 0.87713097, 0.87576206, 0.45924109, 0.57861838],
       [0.35176071, 0.8288533 , 0.44128122, 0.79732528, 0.34296071],
       [0.31051913, 0.44899256, 0.91587882, 0.20653487, 0.06429239],
       [0.92712852, 0.73555388, 0.84575237, 0.07835244, 0.22481925],
       [0.86823526, 0.48125145, 0.42416677, 0.70081709, 0.38932363],
       [0.72356205, 0.95216341, 0.39680908, 0.87109203, 0.7769021 ],
       [0.36501708, 0.20384152, 0.4531161 , 0.38071829, 0.18384882],
       [0.60585984, 0.12877656, 0.93462732, 0.44645968, 0.761247  ],
       [0.03046927, 0.23549773, 0.95594511, 0.33063498, 0.87160176],
       [0.39073941, 0.78146196, 0.46042978, 0.1701343 , 0.24417127]])

In [117]:
matriz + np.array([1,2,3,4,5])

array([[1.90486208, 2.87713097, 3.87576206, 4.45924109, 5.57861838],
       [1.35176071, 2.8288533 , 3.44128122, 4.79732528, 5.34296071],
       [1.31051913, 2.44899256, 3.91587882, 4.20653487, 5.06429239],
       [1.92712852, 2.73555388, 3.84575237, 4.07835244, 5.22481925],
       [1.86823526, 2.48125145, 3.42416677, 4.70081709, 5.38932363],
       [1.72356205, 2.95216341, 3.39680908, 4.87109203, 5.7769021 ],
       [1.36501708, 2.20384152, 3.4531161 , 4.38071829, 5.18384882],
       [1.60585984, 2.12877656, 3.93462732, 4.44645968, 5.761247  ],
       [1.03046927, 2.23549773, 3.95594511, 4.33063498, 5.87160176],
       [1.39073941, 2.78146196, 3.46042978, 4.1701343 , 5.24417127]])

In [119]:
list(filter(lambda x: x>0.5, vector))

[0.6266171605963531, 0.5010284636312075]

In [120]:
vector

array([0.12853713, 0.62661716, 0.50102846, 0.4953363 , 0.35817228])

In [121]:
list(filter(lambda x: x>0.5, matriz[0]))

[0.9048620774288388,
 0.8771309709176769,
 0.8757620576716888,
 0.5786183786772984]

In [122]:
list(filter(lambda x: x>0.5, matriz.flatten()))

[0.9048620774288388,
 0.8771309709176769,
 0.8757620576716888,
 0.5786183786772984,
 0.8288532976907179,
 0.7973252770406675,
 0.9158788240036452,
 0.9271285211206118,
 0.7355538840826737,
 0.8457523700584322,
 0.8682352615646561,
 0.7008170942495212,
 0.7235620472064006,
 0.9521634077001998,
 0.8710920311958733,
 0.7769020956293169,
 0.605859835745676,
 0.9346273155036717,
 0.761247000405622,
 0.955945105537743,
 0.8716017642522261,
 0.7814619595789468]